version: '3'

services:
  app:
    image: cubone-ws
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      REDIS_ADDRESS: "redis:6379"
      ADDR: "0.0.0.0:11888"
    depends_on:
      - redis
    ports:
      - '11888:11888'
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'